mod13/second_part/hm_project/app_auth/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from . import views
from .forms import LoginForm

app_name = 'app_auth'

urlpatterns = [
    path('signup/', views.RegisterView.as_view(), name='signup'), # app_photo:signup, тепер ідемо в views
    path('signin/', LoginView.as_view(template_name='app_auth/login.html', form_class=LoginForm, redirect_authenticated_user=True), name='signin'), # app_photo:signin, тепер ідемо в views
    path('logout/', views.logout_view, name='logout'), # app_photo:logout, тепер ідемо в views
]

mod13/second_part/hm_project/hm_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("quotes.urls")),
    path('auth/', include('app_auth.urls')),
    path('admin/', admin.site.urls),
    # path("users/", include("users.urls"))
]

mod13/second_part/hm_project/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name="root"),
    path('authors/', views.author_detail, name='base'),
    path('<int:page>', views.main, name="root_paginate"),
    path('add_author/', views.add_author, name='add_author'),
    path('author/<int:id>/', views.author_detail, name='author_detail'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('delete_quote/<quote_id>', views.delete_quote, name='delete_quote'),
    path('tag/<str:tag_name>/', views.TagQuotesView.as_view(), name='tag_quotes'),
]

mod13/second_part/hm_project/quotes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname

class Tag(models.Model):
    name = models.CharField(max_length=60, null=False, unique=True)

    class Meta:
        verbose_name_plural = "Tags"
        verbose_name = "Tag"

    def __str__(self):
        return self.name

class Quote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

mod13/second_part/hm_project/quotes/forms.py
# from django.forms import ModelForm, CharField, ImageField, TextInput, FileInput

# from .models import Author

from django import forms
from .models import Quote, Author, Tag


class QuoteForm(forms.ModelForm):
    quote = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control", "rows": "5"}))
    author = forms.ModelChoiceField(
        queryset=Author.objects.all().order_by("fullname"),
        empty_label="Select author",
        to_field_name='fullname',
        widget=forms.Select(attrs={"class": "form-select"}))
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all().order_by("name"),
        widget=forms.SelectMultiple(attrs={"size": "7"}),
        required=False)
    new_tags = forms.CharField(required=False, max_length=30)

    class Meta:
        model = Quote
        fields = ["quote", "author", "tags", "new_tags"]


class AuthorForm(forms.ModelForm):
    fullname = forms.CharField(max_length=64, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    born_date = forms.CharField(max_length=64, help_text="Please follow the format: December 25, 2000.",
                                widget=forms.TextInput(attrs={"class": "form-control"}))
    born_location = forms.CharField(max_length=256, help_text="Please follow the format: in Florida, USA.",
                                    widget=forms.TextInput(attrs={"class": "form-control"}))
    description = forms.Textarea(attrs={"class": "form-control"})

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']
        

mod13/second_part/hm_project/quotes/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, Http404
from .forms import AuthorForm, QuoteForm
from .models import Author, Quote, Tag
from django.views import View
from django.db.models import Count
# Create your views here.
from .utils import get_mongodb

def main(request, page=1):
    db = get_mongodb()
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    top_tags = Tag.objects.annotate(tag_count=Count("quote")).order_by("-tag_count")[:10]
    return render(request, 'quotes/index.html', context={"top_tags": top_tags, "quotes": quotes_on_page})



def author_detail(request, id):
  author = Author.objects.get(pk=id)
  return render(request, 'quotes/author_detail.html', context={'author': author})


@login_required
def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        author_form = AuthorForm(request.POST)

        if form.is_valid():
            author_name = request.POST.get('author')
            author, created = Author.objects.get_or_create(fullname=author_name, defaults={'user': request.user})

            quote = form.save(commit=False)
            quote.user = request.user
            quote.author = author
            quote.save()

            tags = form.cleaned_data['tags']
            new_tags = request.POST.get('new_tags')
            if new_tags:
                new_tag_objects = [Tag.objects.get_or_create(name=tag.strip())[0] for tag in new_tags.split(',')]
                quote.tags.add(*new_tag_objects)
            quote.tags.add(*tags)
            return redirect("/")
    else:
        form = QuoteForm()
        author_form = AuthorForm()

    return render(request, "quotes/add_quote.html", {"form": form, 'author_form': author_form})


@login_required
def delete_quote(request, quote_id):
    quote = get_object_or_404(Quote, id=quote_id)

    if request.user.is_authenticated and quote.user == request.user:
        quote.delete()
        return redirect('/')
    else:
        return JsonResponse({'message': 'Your access was not authorized or Quote does not exist.'}, status=401)


@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = AuthorForm()

    return render(request, "quotes/add_author.html", {"form": form})

class TagQuotesView(View):
    template_name = 'quotes/tag_quotes.html'
    quotes_per_page = 10

    def get(self, request, *args, **kwargs):
        tag_name = kwargs['tag_name']
        top_tags = Tag.objects.annotate(tag_count=Count("quote")).order_by("-tag_count")[:10]
        tag = get_object_or_404(Tag, name=tag_name)
        quotes_with_tag = get_list_or_404(Quote.objects.filter(tags=tag))

        paginator = Paginator(quotes_with_tag, self.quotes_per_page)
        page = request.GET.get('page')

        try:
            quotes_per_page = paginator.page(page)
        except (PageNotAnInteger, EmptyPage):
            quotes_per_page = paginator.page(1)

        context = {
            'tag_name': tag_name,
            'quotes_with_tag': quotes_per_page,
            "top_tags": top_tags
        }

        return render(request, self.template_name, context)

mod13/second_part/hm_project/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="author-details ms-5" style="margin-left: 10%;">
    <h1>Add New Author</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-danger">Reset</button>
    </form>
</div>

{% endblock %}

mod13/second_part/hm_project/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %} {% block content %}
<h1>Add quote</h1>
<form method="post">
    {% csrf_token %}
    <div class="form_row">
        <div class="mb-3">
            <label class="form-label">Quote</label>
            {{ form.quote }}
        </div>
        <span>{{form.errors.quote}}</span>
    </div>
    <div class="form_row">
        <div class="mb-3">
            <label class="form-label">Автор</label>
            {{ form.author }}
        </div>
        <span>{{form.errors.author}}</span>
    </div>
    <div class="form_row">
        <div class="mb-3">
            <label class="form-label">Виберіть тег: </label>
            {{form.tags}}
        </div>
        <input type="text" name="new_tags" class="form-control" placeholder="Enter new tag(s)">
    </div>
    <button type="submit" class="btn btn-primary">Додати тег</button>
</form>

{% endblock %}

mod13/second_part/hm_project/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}
{% load extract_authors %}

{% block content %}

<div class="author-details ms-5 me-5">
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Народився:</strong>
        <span class="author-born-date">{{ author.born_date }}</span>
        <span class="author-born-location">{{ author.born_location }}</span>
    </p>
    <p><strong>Опис:</strong></p>
    <div class="author-description me-5">
        {{ author.description }}
    </div>

</div>

{% endblock %}

mod13/second_part/hm_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/styles.css' %}">
    <title>Homework 10</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8" style="padding-bottom: 40px;">
            <h1><a href="/" style="text-decoration: none">Quotes to Scrape</a></h1>
        </div>
        <div class="col-md-4" style="flex-direction: row-reverse;">
            <div style="display: flex; gap: 15px">
                {% if user.is_authenticated %}
                <a href="{% url 'quotes:add_author' %}" class="btn btn-primary" style="height: 38px">Upload</a>
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary" style="height: 38px">Add quote</a>
                <form action="{% url 'app_auth:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" style="margin-right: 15px">Log out</button>
                </form>
                {% else %}
                <p style="margin: 0px"><a class="btn btn-primary" href="{% url 'app_auth:signup' %}">Register</a></p>
                <p style="margin: 0px"><a class="btn btn-primary" href="{% url 'app_auth:signin' %}">Login</a></p>
                {% endif %}
            </div>
        </div>
            {% block content %}
            {% endblock %}
        </div>
</div>
</body>
</html>

mod13/second_part/hm_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}
                <span style="float: right;">
                    {% if user.is_authenticated and quote.user == user %}
                        <form method="post" action="{% url 'quotes:delete_quote' quote.id %}">
                            {% csrf_token %}
                            <button class="btn btn-danger" type="submit">DELETE</button>
                        </form>
                    {% endif %}
                </span>
            </span>
            <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small><a href="{% url 'quotes:author_detail' id=quote.author.id %}" target="_self"> (about)</a></span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>

        {% endfor %}

        <nav>
            <ul class="pager">
                <li class="btn btn-secondary">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}" href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}"><span aria-hidden="true">←</span> Previous</a>
                </li>
                <li class="btn btn-secondary">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}" href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next <span aria-hidden="true">→</span></a>
                </li>
            </ul>
        </nav>
    </div>

    <div class="col-md-4 tags-box" style="display: flex; flex-direction: column;">
        {% load extract %}
        <h2>Top Ten tags</h2>
        {% for tag in top_tags %}
        <span class="tag-item"><a class="tag" href="/tag/{{ tag }}">{{ tag }}</a></span>
        {% endfor %}
    </div>


</div>

{% endblock %}

mod13/second_part/hm_project/quotes/templates/quotes/tag_quotes.html
{% extends 'quotes/base.html' %}
{% load extract_authors %}

{% block content %}

<div class="author-details ms-5" style="margin-left: 10%;">
    <h2 class="author-title" style="margin-left: 5%;">
        Viewing tag: <b style="color:dodgerblue;">{{ tag_name }}</b>
    </h2>
    <div class="col-md-8">

        {% for quote in quotes_with_tag %}

        <div class="quote ms-5" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text"> {{quote.quote}}
                <span style="float: right;">
                    {% if user.is_authenticated and quote.user == user %}
                        <form method="post" action="{% url 'quotes:delete_quote' quote.id %}">
                            {% csrf_token %}
                            <button class="btn btn-danger" type="submit">DELETE</button>
                        </form>
                    {% endif %}
                </span>
            </span>
            <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small><a href="{% url 'quotes:author_detail' id=quote.author.id %}" target="_self"> (about)</a></span>
            <div class="tags">
                Tags:
                <meta class="keywords" itemprop="keywords"
                      content="{% for tag in quote.tags.all %}{{ tag.name }},{% endfor %}">
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:tag_quotes' tag_name=tag.name %}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>

        {% endfor %}

        <nav>
            <div class="pagination" class="mb-3">
                <span class="step-links" style="margin-left: 5%;">
                    {% if quotes_with_tag.has_previous %}
                        <a class="btn btn-secondary" href="?page={{ quotes_with_tag.previous_page_number }}">Previous</a>
                    {% endif %}

                    <span class="current" style="margin: 0 10px;"><strong>Page {{ quotes_with_tag.number }} from {{ quotes_with_tag.paginator.num_pages }}.</strong></span>

                    {% if quotes_with_tag.has_next %}
                        <a class="btn btn-secondary" href="?page={{ quotes_with_tag.next_page_number }}">Next</a>
                    {% endif %}
                </span>
            </div>
        </nav>

    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

{% endblock %}

mod13/second_part/hm_project/quotes/templates/quotes/upload.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-3">
    {% if form.errors and form.not_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.not_field_errors}}
    </div>
    {% endif %}
    <!--    <form action="{% url 'quotes:upload' %}" method="post" , enctype="multipart/form-data">-->
    <!--        {% csrf_token %}-->
    <!--        <div class="mb-3">-->
    <!--            <label for="exampleInputEmail1" class="form-label">fullname</label>-->
    <!--            <label for="exampleInputEmail1" class="form-label">fullname</label>-->
    <!--            <label for="exampleInputEmail1" class="form-label">fullname</label>-->
    <!--            <label for="exampleInputEmail1" class="form-label">Description</label>-->
    <!--            {{ form.description }}-->
    <!--            <div id="emailHelp" class="form-text">Description for picture</div>-->
    <!--            <span>{{form.errors.description}}</span>-->
    <!--        </div>-->
    <!--        <div class="mb-3">-->
    <!--            <label for="formFile" class="form-label">Default file input example</label>-->
    <!--            {{form.path}}-->
    <!--            <span>{{form.errors.path}}</span>-->
    <!--        </div>-->
    <!--        &lt;!&ndash;          <div class="mb-3">&ndash;&gt;-->
    <!--        &lt;!&ndash;            <label for="exampleInputPassword1" class="form-label">Password</label>&ndash;&gt;-->
    <!--        &lt;!&ndash;            <input type="password" class="form-control" id="exampleInputPassword1">&ndash;&gt;-->
    <!--        &lt;!&ndash;          </div>&ndash;&gt;-->
    <!--        &lt;!&ndash;          <div class="mb-3 form-check">&ndash;&gt;-->
    <!--        &lt;!&ndash;            <input type="checkbox" class="form-check-input" id="exampleCheck1">&ndash;&gt;-->
    <!--        &lt;!&ndash;            <label class="form-check-label" for="exampleCheck1">Check me out</label>&ndash;&gt;-->
    <!--        &lt;!&ndash;          </div>&ndash;&gt;-->
    <!--        <button type="submit" class="btn btn-primary">Submit</button>-->
    <!--        <button type="reset" class="btn btn-danger">Reset</button>-->
    <!--    </form>-->
    <h1>Add New Author</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}